### ISSUE TITLE
Capybara Lockstep fails to synchronize when accessing second iframe

### ISSUE THREAD

**Issue by dfritsch** [makandra/capybara-lockstep#4]
I am using a third party tool that adds content to the page via iframes. Specifically, it will launch a _second_ iframe when something is clicked via a first iframe. I'm not specifically sure if this issue requires two iframes or is a more broad problem with `within_frame`.

The example rspec looks like this:

```
  it "checks for content in second iframe" do
      puts "Attempting to find first iframe"
      page.within_frame(find("#launcher", wait: 8.seconds)) do
        puts "in frame"
        expect(page).to have_button("Support")
        click_on("Support")
      end

      puts "Attempting to find second iframe"
      page.within_frame(find("#webWidget")) do
        puts "in frame"
        expect(find_all("ol li").count).to be >= 3
      end
  end
```

I've added some debugging `puts` statements to help match things with the debug output. With `Capybara::Lockstep.debug = true` and the puts above, this ends up outputting:

```
Attempting to find first iframe
[capybara-lockstep] Synchronizing
[capybara-lockstep] Could not synchronize within 5 seconds
[capybara-lockstep] Synchronizing
[capybara-lockstep] Could not synchronize within 5 seconds
[capybara-lockstep] Synchronizing
[capybara-lockstep] Could not synchronize within 5 seconds
[capybara-lockstep] Synchronizing
[capybara-lockstep] Could not synchronize within 5 seconds
in frame
[capybara-lockstep] Synchronizing
[capybara-lockstep] Cannot synchronize before initial Capybara visit
[capybara-lockstep] Synchronizing
[capybara-lockstep] Cannot synchronize before initial Capybara visit
[capybara-lockstep] Synchronizing
[capybara-lockstep] Cannot synchronize before initial Capybara visit
[capybara-lockstep] Synchronizing
[capybara-lockstep] Cannot synchronize before initial Capybara visit
[capybara-lockstep] Synchronizing
[capybara-lockstep] Cannot synchronize before initial Capybara visit
[capybara-lockstep] Synchronizing
[capybara-lockstep] Cannot synchronize before initial Capybara visit
[capybara-lockstep] Synchronizing
[capybara-lockstep] Cannot synchronize before initial Capybara visit
[capybara-lockstep] Synchronizing
[capybara-lockstep] Cannot synchronize before initial Capybara visit
[capybara-lockstep] Synchronizing
[capybara-lockstep] Cannot synchronize before initial Capybara visit
Attempting to find second iframe
[capybara-lockstep] Synchronizing
[capybara-lockstep] Could not synchronize within 5 seconds
[capybara-lockstep] Synchronizing
[capybara-lockstep] Could not synchronize within 5 seconds
[capybara-lockstep] Synchronizing
[capybara-lockstep] Could not synchronize within 5 seconds
[capybara-lockstep] Synchronizing
[capybara-lockstep] Could not synchronize within 5 seconds
in frame
```

My assumption is that the frame does not have injected javascript and thus we can not synchronize within the frames?

**Comment by triskweline** [comment]
> My assumption is that the frame does not have injected javascript and thus we can not synchronize within the frames?

It is true that capybara-lockstep can only synchronize with documents that have the JavaScript snippet loaded. However in that case you would get a message `Cannot synchronize: capybara-lockstep JavaScript snippet is missing`. Something else must be wrong here.

> [capybara-lockstep] Could not synchronize within 5 seconds

This error is logged when the JavaScript snippet is present and starts synchronizing, but some async task or remote resource is taking more than 5 seconds to finish. Try looking at your browser console with `Capybara::Lockstep.debug = true` for more information what work capybara-lockstep is waiting for.

> [capybara-lockstep] Cannot synchronize before initial Capybara visit

It might be that your third-party tool is working with [data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) that older versions of capybara-lockstep do not understand. Support for data URLs has been added in version 1.2.1 (released today).

Version 1.2.0 also added [synchronization around frame switches](https://makandracards.com/makandra/516362-capybara-lockstep-1-2-1-and-1-2-0-released) which may or not help you. I think other issues may be present, as outlined above. If nothing else helps you need to disable synchronization in tests that work with the third party widget.

Closing this issue as I can't debug this any further. Good luck!
