### ISSUE TITLE
Handle Capybara Cuprite driver

### ISSUE THREAD

**Issue by navidemad** [makandra/capybara-lockstep#5]
Many people are migrating their tests suite from selenium to cuprite, which is apparently 40% faster and offer lot of cool features. https://cuprite.rubycdp.com/
Are you planning to make it compatible with this gem ?

**Comment by dastra-mak** [comment]
Hi @navidemad, at makandra we're currently not using cuprite and there is no plan to do so in the near future. So currently we won't make it compatible with it.
Maybe this method can help you replacing capybara-lockstep: https://github.com/rubycdp/ferrum#wait_for_idleoptions

**Comment by gap777** [comment]
We're using cuprite as well, and would love to have Lockstep! 
@navidemad Did you find a way to replace it?
