### ISSUE TITLE
Lockstep doesn't synchronize before evaluate_script

### ISSUE THREAD

**Issue by niklas-hasselmeyer** [makandra/capybara-lockstep#8]
I noticed that Capybara::Lockstep doesn't synchronize before a `evaluate_script` call. If this call is the first action after a page load, the result may be wrong.

After some digging around, I found [this comment](https://github.com/makandra/capybara-lockstep/blob/bb6c940f4517535fb651b251763a240d69c7bee4/lib/capybara-lockstep/capybara_ext.rb#L149-L150):
> ```
> Capybara::Session.class_eval do
>   ...
>   synchronize_around_script_method :execute_script
>   synchronize_around_script_method :evaluate_async_script
>
>   # Don't synchronize around evaluate_script. It calls execute_script
>   # internally and we don't want to synchronize multiple times.
> end
> ```
However, `Capybara::Session#evaluate_script` doesn't call `Capybara::Session#execute_script`. It calls `Capybara::Selenium::Driver#evaluate_script`, which calls `Capybara::Selenium::Driver#execute_script`. But as the driver methods are not monkey-patched, `evaluate_script` never runs into Lockstep.

**Comment by triskweline** [comment]
Thanks @niklas-hasselmeyer, we now synchronize around `evaluate_script`.

I also checked if it would be better to patch the `Driver` classes instead, but it looks like the `Node` methods do considerable work before delegating to the driver. So it's better to synchronize before all that work.
